name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test-lint:
    name: Testing and Linting
    runs-on: ubuntu-22.04
    steps:
      # Login to Docker Hub to increase rate limits
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat > .env <<EOF
          DJANGO_SECRET=${{ secrets.DJANGO_SECRET }}
          SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}
          SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
          EOF

      - name: Test
        run: docker compose run -u root --rm backend sh -c "wait-for-it --service db:5432 --timeout 45 -- python manage.py test"

      - name: Lint
        run: docker compose run --rm backend sh -c "flake8"
