name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test-lint:
    name: Testing and Linting
    runs-on: ubuntu-22.04
    steps:
      # Login to Docker Hub to increase rate limits
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat > .env <<EOF
          DJANGO_SECRET=${{ secrets.DJANGO_SECRET }}
          GOOGLE_OAUTH2_CLIENT_ID=${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}
          GOOGLE_OAUTH2_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
          ALLOWED_HOSTS=localhost,127.0.0.1
          SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI=http://localhost:8000/social-auth/complete/google-oauth2/
          SOCIAL_AUTH_LOGIN_REDIRECT_URL=http://localhost:5173/
          CORS_ALLOWED_ORIGINS=http://localhost:5173
          CSRF_TRUSTED_ORIGINS=http://localhost:5173
          EOF

      - name: Test
        run: docker compose run -u root --rm backend sh -c "coverage run --source='.' manage.py test && coverage xml"

      - name: Lint
        run: docker compose run --rm backend sh -c "flake8"

      - name: Upload backend coverage
        uses: codecov/codecov-action@v5
        with:
          files: backend/coverage.xml
          flags: backend

      - name: Security Check
        run: docker compose run --rm backend sh -c "bandit -r ."
